### ISSUE TITLE
Doesn't work in React Native.

### ISSUE THREAD

**Issue by shuiRong** [plantain-00/relative-time-component#2]
#### Environment(if relevant):
"react": "16.6.3",
"react-native": "0.57.1",
yarn: 1.12.3
npm: 6.4.1
node: v10.0.0
macOS: 10.14.2

#### Code(if relevant):

```
import { RelativeTime } from 'relative-time-react-component'

...

<RelativeTime time={1545835171000} />

```

#### Expected:

the correct relative time string

#### Actual:

![screenshot_2018-12-26-23-12-33-841_com gakki2](https://user-images.githubusercontent.com/16076993/50449752-3447a180-0964-11e9-8362-6becd91ee0b3.png)

#### More:
I hope that you have tested the component in react native truely.
the `span` element is not allowed in react-native as picture shows.

**Comment by plantain-00** [comment]
I think you should use `relative-time-react-native-component` rather than `relative-time-react-component`

**Comment by shuiRong** [comment]
It's my mistake.
