### ISSUE TITLE
weird problem: naming collision

### ISSUE THREAD

**Issue by shuiRong** [plantain-00/relative-time-component#3]
#### Version(if relevant): 1.0.0

"relative-time-react-native-component": "^4.5.1"

#### Environment(if relevant):

react: "16.6.3",
react-native: "0.57.1",
yarn: 1.12.3
npm: 6.4.1
node: v10.0.0
macOS: 10.14.2

#### Code(if relevant):

```
import { RelativeTime } from 'relative-time-react-component'

...

<RelativeTime time={1545835171000} />
```

#### Actual:
**look the screenshots:**
![image](https://user-images.githubusercontent.com/16076993/50540252-6148be00-0bc9-11e9-96d0-733c4bf1004a.png)
![image](https://user-images.githubusercontent.com/16076993/50540268-c3a1be80-0bc9-11e9-9ba4-efcfa49674d1.png)

If I delete the `node_modules/relative-time-react-component/node_modules` manually, the problem will be gone. It's weird.

**Comment by plantain-00** [comment]
It seems you installed 2 `react-native` package, you can check it by `yarn list --pattern react-native`.

You can google the solution, usually just merge them in `yarn.lock`, then `yarn` again

**Comment by shuiRong** [comment]
I delete the `"react-native": "*"` in yarn.lock and reinstall node_modules, the problem is gone.

**Comment by shuiRong** [comment]
> I delete the `"react-native": "*"` in yarn.lock and reinstall node_modules, the problem is gone.

The reasonable way: https://github.com/aws/awsmobile-cli/issues/172#issuecomment-455737267
